from Tkinter import *
root=Tk()
Label(root,text='Your Personal Details',relief='ridge',font='times 20 bold italic underline').pack()
Label(root,text='Enter Your Name:').pack()
e1=Entry()
e1.pack()
Label(root,text='Enter your DoB in DD/MM/YYYY:').pack()
e2=Entry()
e2.pack()
v2=IntVar()
v3=IntVar()
v4=IntVar()
Label(root,text='Select Your Highest Qualification : ').pack()
Checkbutton(root,text='B.Tech',variable=v2,onvalue=1).pack()
Checkbutton(root,text='M.Tech',variable=v3,onvalue=2).pack()
Checkbutton(root,text='Ph.D.',variable=v4,onvalue=3).pack()
Label(root,text='Please Select Your Branch').pack()
v5=IntVar()
r=Radiobutton(root,text='CSE',variable=v5,value=1)
r.pack()
r2=Radiobutton(root,text='ECE',variable=v5,value=2)
r2.pack()
r3=Radiobutton(root,text='ME',variable=v5,value=3)
r3.pack()
r4=Radiobutton(root,text='CE',variable=v5,value=4)
r4.pack()
r5=Radiobutton(root,text='CHE',variable=v5,value=5)
r5.pack()
def SeeDetails():
    if v2.get()==1 and v5.get==1:
        Label(root,text='B.Tech CSE').pack()
    elif v3.get()==2:
        Label(root,text='M.Tech').pack()
    elif v4.get()==3:
        Label(root,text='Ph.D').pack()
Button(root,text='See Details',command=SeeDetails).pack()
mainloop()
